keep-starknet-strange/snos

src/pie.rs

dev: group like fn sigs

---

Cargo.toml
src/error/mod.rs
src/lib.rs
src/sharp/mod.rs
src/sharp/pie.rs
tests/pie.rs
tests/sharp.rs

update sharp utils and enable sharp client

dev: update sharp utils

---

src/error.rs
src/hints/mod.rs
src/io.rs
src/io/classes.rs
src/io/mod.rs
src/lib.rs
src/state/mod.rs
src/state/node.rs
src/state/storage.rs
src/utils.rs
tests/common/mod.rs
tests/common/os_input.json
tests/common/syscall_handler_test.py
tests/snos.rs

feat: serializer

---

scripts/debug-hint.sh
scripts/setup-tests.sh
src/config.rs
src/hints/block_context.rs
src/hints/hints_raw.rs
src/hints/mod.rs
src/io/mod.rs
src/lib.rs
src/utils.rs
tests/common/mod.rs
tests/common/os_input.json
tests/common/serde.rs
tests/common/utils.rs
tests/hints.rs
tests/programs/initialize_state_changes.cairo
tests/programs/load_deprecated_class.cairo
tests/snos.rs

- insert os_path + block_context via runner memory
- refactor block_context
- add to block_context
- initialize state changes + test
- move json deserialize hack to tests

track-1: block context

---

src/hints/hints_raw.rs
src/hints/mod.rs

- segment add
- temporary segment add
- transaction len add
- hint stub for syscall scopes

track-2: syscall prep

---

.github/workflows/check.yml
tests/sharp.rs

fix: ci hotfix

---

Cargo.lock
Cargo.toml
src/state/mod.rs
src/utils.rs

remove forks, remove aliased dependencies

dev: dep resolution

---

src/hints/builtins.rs
tests/snos.rs

Fix `update_builtin_ptrs`

---

examples/hints.rs
src/hints/block_context.rs
src/hints/execution.rs

Improve `hints_stats`

---

.github/workflows/check.yml
rust-toolchain
walkthrough.md

walkthrough

---

.gitignore

This file is automatically generated when running tests.
- [] dev (no functional changes, no API changes)
- [] testing

Fix: delete `os_latest.json`

---

src/hints/unimplemented.rs

This hint is already implemented as START_TX.

Cleanup: SET_TX_INFO_PTR is already implemented

---

src/config.rs
src/execution/helper.rs
src/hints/mod.rs
src/hints/state.rs
src/hints/unimplemented.rs
src/hints/vars.rs
src/io/input.rs
src/io/mod.rs
src/starknet/starknet_storage.rs
src/state/mod.rs

Feature: SET_INITIAL_STATE_PTR hint

---

src/hints/execution.rs
src/hints/mod.rs
src/hints/types.rs
src/hints/unimplemented.rs
src/hints/vars.rs
src/starkware_utils/commitment_tree/update_tree.rs

Feature: ENTER_SCOPE_NEW_NODE hint

---

src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: ADD_RELOCATION_RULE hint

---

src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: SET_AP_TO_TX_NONCE hint

---

src/cairo_types/mod.rs
src/cairo_types/syscalls.rs
src/execution/helper.rs
src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs
src/starknet/starknet_storage.rs

Feature: WRITE_SYSCALL_RESULT hint

---

src/hints/mod.rs
src/hints/patricia.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: SET_SIBLINGS hint

---

src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs
src/io/mod.rs
tests/common/transaction_utils.rs

Feature: GEN_NONCE_ARG hint

---

src/hints/mod.rs
src/hints/patricia.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: IS_CASE_RIGHT hint

---

src/hints/mod.rs
src/hints/output.rs
src/hints/unimplemented.rs

Feature: SET_AP_TO_BLOCK_HASH hint

---

src/cairo_types/trie.rs
src/hints/mod.rs
src/hints/patricia.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: SET_BIT hint

---

src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Implemented:
* ENTER_SCOPE_DESCEND_EDGE
* ENTER_SCOPE_LEFT_CHILD
* ENTER_SCOPE_RIGHT_CHILD
* ENTER_SCOPE_NODE
* ENTER_SCOPE_NEXT_NODE_BIT_1
* ENTER_SCOPE_NEXT_NODE_BIT_0

Feature: implement all node scope hints

---

src/hints/mod.rs
src/hints/patricia.rs

Feature: ASSERT_CASE_IS_RIGHT hint

---

src/hints/mod.rs
src/hints/patricia.rs
src/hints/types.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: SET_AP_TO_DESCEND hint

---

src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs

Feature: SET_AP_TO_NONCE_ARG_SEGMENT hint

---

src/cairo_types/syscalls.rs
src/hints/mod.rs
src/hints/syscalls.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Implemented the following hints:
* CHECK_SYSCALL_RETURN_VALUE
* CHECK_NEW_SYSCALL_RETURN_VALUE
* CHECK_NEW_DEPLOY_RETURN_VALUE

Feature: CHECK_*_RETURN_VALUE hints

---

src/hints/mod.rs
src/hints/patricia.rs
src/hints/unimplemented.rs

Feature: SPLIT_DESCEND hint

---

src/cairo_types/entry_point.rs
src/cairo_types/mod.rs
src/execution/syscall_handler.rs
src/hints/mod.rs
src/hints/syscalls.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: VALIDATE_AND_DISCARD_SYSCALL_PTR hint

---

src/hints/mod.rs
src/hints/state.rs
src/hints/unimplemented.rs

Feature: LOAD_BOTTOM hint

---

src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: WRITE_OLD_BLOCK_TO_STORAGE hint

---

src/execution/helper.rs
src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs

Feature: GET_OLD_BLOCK_NUMBER_AND_HASH hint

---

src/hints/mod.rs
src/hints/patricia.rs
src/hints/unimplemented.rs

Feature: HEIGHT_IS_ZERO_OR_LEN_NODE_PREIMAGE_IS_TWO hint

---

src/hints/mod.rs
src/hints/patricia.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: PREPARE_PREIMAGE_VALIDATION_NON_DETERMINISTIC_HASHES hint

---

.github/CODEOWNERS

CI: update maintainers

---

src/execution/execute_syscalls.rs
src/hints/block_context.rs
src/hints/builtins.rs
src/hints/mod.rs
src/hints/patricia.rs

Cleanup: Build Felt from bool directly

---

src/hints/execution.rs
src/hints/unimplemented.rs

This hint is already implemented as
GET_CONTRACT_ADDRESS_STATE_ENTRY_AND_SET_NEW_STATE_ENTRY.

Cleanup: ASSIGN_STATE_ENTRY_WITH_NEW_SEGMENT is already implemented

---

src/hints/mod.rs
src/hints/transaction_hash.rs
src/hints/unimplemented.rs

Feature: ADDITIONAL_DATA_NEW_SEGMENT hint

---

src/hints/state.rs
src/hints/vars.rs
src/utils.rs

Fix: ids.MERKLE_HEIGHT is a constant

---

src/hints/compiled_class.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs
src/starknet/core/mod.rs
src/starknet/core/os/contract_class/compiled_class_hash_objects.rs
src/starknet/core/os/contract_class/mod.rs
src/starknet/core/os/mod.rs
src/starknet/mod.rs

Feature: ASSIGN_BYTECODE_SEGMENTS hint

---

src/hints/mod.rs
src/hints/output.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: SET_STATE_UPDATES_START hint

---

src/hints/mod.rs
src/hints/syscalls.rs
src/hints/unimplemented.rs

Implements the simple `EXIT_GET_BLOCK_NUMBER_SYSCALL` hint.

Impl EXIT_GET_BLOCK_NUMBER_SYSCALL hint

---

src/hints/mod.rs
src/hints/patricia.rs
src/hints/unimplemented.rs
src/starkware_utils/commitment_tree/update_tree.rs

Implements the simple WRITE_CASE_NOT_LEFT_TO_AP hint.

Feature: Impl WRITE_CASE_NOT_LEFT_TO_AP

---

src/hints/unimplemented.rs

This hint is already implemented as
IS_BLOCK_NUMBER_IN_BLOCK_HASH_BUFFER.

Cleanup: CHECK_REQUEST_BLOCK_AGAINST_BUFFER_LEN is already implemented

---

src/hints/bls_utils.rs
src/hints/mod.rs
src/hints/state.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Implements the `WRITE_SPLIT_RESULT` hint (renamed from `WRITE_ADDRESS`)

Feature: Impl WRITE_SPLIT_RESULT

---

src/cairo_types/bigint.rs
src/cairo_types/mod.rs
src/hints/bls_field.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: COMPUTE_IDS_LOW hint

---

src/hints/execute_transactions.rs
src/hints/mod.rs
src/hints/output.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: START_TX_VALIDATE_DECLARE_EXECUTION_CONTEXT hint

---

src/cairo_types/syscalls.rs
src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: SET_STATE_ENTRY_TO_ACCOUNT_CONTRACT_ADDRESS hint

---

src/hints/execution.rs
src/hints/mod.rs
src/hints/unimplemented.rs
src/hints/vars.rs

Feature: FETCH_RESULT hint

---

src/execution/syscall_handler.rs
src/execution/syscall_utils.rs
src/execution/syscalls.rs
tests/common/transaction_utils.rs
tests/os.rs

Feature: handle cairo1 `send_message_to_l1` syscall

---

src/execution/execute_syscalls.rs

Fix: Integrate lc cairo-vm fix, remove workaround

---

src/hints/block_context.rs
src/hints/deprecated_compiled_class.rs
src/hints/mod.rs

This makes it easier to identify changes related to hashing.

Internal: move Cairo 0 hash-related hints to dedicated module

---

src/hints/tests.rs

Fix:occurences->occurrences

---

src/cairo_types/syscalls.rs
src/execution/deprecated_syscall_handler.rs
src/hints/syscalls.rs
tests/integration/contracts/blockifier_contracts/feature_contracts/cairo0/compiled/test_contract_compiled.json
tests/integration/contracts/blockifier_contracts/feature_contracts/cairo0/test_contract.cairo
tests/integration/syscalls_tests.rs

Added a dedicated test in the Cairo 0 test contract.

Feature: get_tx_signature syscall

---

src/execution/deprecated_syscall_handler.rs
src/hints/syscalls.rs
tests/integration/syscalls_tests.rs

Feature: support Cairo 0 `replace_class()` syscall

---

src/cairo_types/syscalls.rs
src/execution/deprecated_syscall_handler.rs
src/hints/syscalls.rs
tests/integration/syscalls_tests.rs

Feature: support `get_contract_address()` Cairo 0 syscall

---

src/execution/deprecated_syscall_handler.rs
src/hints/syscalls.rs
tests/integration/contracts/blockifier_contracts/feature_contracts/cairo0/compiled/test_contract_compiled.json
tests/integration/contracts/blockifier_contracts/feature_contracts/cairo0/test_contract.cairo
tests/integration/deprecated_syscalls_tests.rs

Feature: support `emit_event` Cairo0 syscall

---

src/execution/deprecated_syscall_handler.rs
src/hints/syscalls.rs
tests/integration/contracts/blockifier_contracts/feature_contracts/cairo0/compiled/test_contract_compiled.json
tests/integration/contracts/blockifier_contracts/feature_contracts/cairo0/test_contract.cairo
tests/integration/deprecated_syscalls_tests.rs

Feature: support `send_message` Cairo 0 syscall

---

src/io/output.rs
src/lib.rs

Problem: To integrate the OS with other applications, developers requested that the OS output must implement `Serialize` and `Deserialize`.
Solution: derive these traits for the OS output.
Resolves #244.

Feature: make the OS output serializable and deserializable

---

tests/integration/common/transaction_utils.rs
tests/integration/declare_txn_tests.rs

Feature: support declare v3 txs

---

tests/integration/common/transaction_utils.rs
tests/integration/declare_txn_tests.rs

Problem: Functionality related to declare v1 is currently not tested.
Solution: Implement the pending tests.

Feature: Declare v1 Support

---

src/execution/deprecated_syscall_handler.rs
src/execution/helper.rs
src/hints/execution.rs
src/hints/syscalls.rs
src/hints/vars.rs
tests/integration/common/state.rs
tests/integration/common/transaction_utils.rs
tests/integration/deploy_txn_tests.rs
tests/integration/main.rs

Problem: deploy account checks and tests are not implemented.
Solution: Implement the missing parts.

Feature: Support `deploy_account` v1 txns

---

.github/workflows/check.yml

Chore: bump cairo-lang version to 0.13.1 in CI

---

.github/workflows/check.yml

Internal: name individual CI steps

---

Cargo.lock

Chore: bump cairo-vm to latest

---

Cargo.toml
crates/starknet-os/Cargo.toml
crates/starknet-os/src/utils.rs

Marked all functions as `pub(crate)` to detect dead code in this module in the future.

Internal: remove dead code in utils module

---

crates/starknet-os/src/error.rs

Internal: remove dead code from the error module

---

tests/integration/common/blockifier_contracts.rs
tests/integration/common/state.rs
tests/integration/common/utils.rs
tests/integration/declare_txn_tests.rs
tests/integration/deploy_txn_tests.rs

Internal: move Blockifier specific code to the correct module

---

Cargo.toml
crates/bin/prove_block/Cargo.toml
crates/bin/prove_block/src/main.rs
crates/bin/prove_block/src/rpc_utils.rs
crates/bin/prove_block/src/types.rs

A follow up from #287 to clean things up.

Pathfinder integration cleanup

---

crates/bin/prove_block/src/types.rs

Currently only Invoke TX is supported, this PR incorporates:
- DECLARE
- DEPLOY_ACCOUNT
- L1_HANDLER

Feature: Handle all tx types in starknet_rs_tx_to_internal_tx

---

crates/bin/prove_block/src/rpc_utils.rs

This PR adds proof verification of contract state proofs. Essentially, it adapts the class proof verification done by @odesenfans to work for storage proofs.
TODO:

Contract state proof verification

---

crates/bin/prove_block/src/main.rs
crates/bin/prove_block/src/rpc_utils.rs
crates/bin/prove_block/src/utils.rs

Problem: prove_block main.rs is now super big as a result of lot of exploration 
Solution: Modularize it and move code into other files

chore: handle contract subcalls outside main.rs

---

crates/bin/prove_block/src/rpc_utils.rs
crates/bin/prove_block/src/utils.rs

Problem: we need to modularize prove_block binary
Solution: modularize
⚠️ Please run prove_block with our successful block to ensure that we dont get regressions

chore: move TxExecutionInfo processing from rpc_utils to utils

---

crates/bin/prove_block/src/main.rs
crates/bin/prove_block/src/state_utils.rs

Problem: we need to modularize prove_block binary
Solution: modularize
⚠️ Please run prove_block with our successful block to ensure that we dont get regressions

chore: move build_initial_state from main to state_utils

---

crates/starknet-os/src/hints/compiled_class.rs

Add a unit test for `iter_current_segment_info` hint. Using 3 different `BytecodeSegment` struct, call the hint and then verify that the stored information matches the test reference.

Tests for iter_current_segment_info

---

crates/bin/prove_block/src/reexecute.rs

Problem: it is hard to which transaction fails when an error occur during reexecution.
Solution: add the tx hash and enumerate transactions in the logs to identify failures more easily.

Internal: improve logging on Blockifier reexecution

---

crates/bin/prove_block/Cargo.toml
crates/bin/prove_block/src/main.rs
crates/bin/prove_block/src/state_utils.rs

Problem: we need to modularize prove_block binary
Solution: modularize
⚠️ Please run prove_block with our successful block to ensure that we dont get regressions

Chore: refactor prove block state functions

---

crates/bin/prove_block/src/main.rs
crates/bin/prove_block/src/rpc_utils.rs
crates/bin/prove_block/src/state_utils.rs

Problem: all the code related with build_initial_state was useful
Solution: remove it

Chore: remove build_initial_state

---

.github/workflows/prove_block.yml
.github/workflows/prove_blocks.yml
scripts/prove-blocks.sh

Problem: Currently there is no way to run the `prove_block` command against several blocks in the CI.
Solution: Implement a way to start pathfinder and prove blocks.

Testing: Allow proving of blocks in CI

---

scripts/setup-tests.sh

Chore: bump cairo-lang to v0.13.2

---

.github/workflows/check.yml
.github/workflows/prove_blocks.yml
Cargo.toml
crates/bin/prove_block/src/lib.rs
crates/bin/prove_block/src/main.rs
crates/bin/prove_block/tests/prove_block.rs
crates/starknet-os/src/config.rs
crates/starknet-os/src/execution/syscall_handler.rs
crates/starknet-os/src/hints/block_context.rs
crates/starknet-os/src/hints/execute_transactions.rs
crates/starknet-os/src/hints/execution.rs
crates/starknet-os/src/hints/find_element.rs
crates/starknet-os/src/hints/mod.rs
crates/starknet-os/src/hints/os.rs
crates/starknet-os/src/hints/output.rs
crates/starknet-os/src/hints/state.rs
crates/starknet-os/src/hints/unimplemented.rs
crates/starknet-os/src/hints/vars.rs
crates/starknet-os/src/io/input.rs
crates/starknet-os/src/io/output.rs
crates/starknet-os/src/lib.rs
crates/starknet-os/src/utils.rs
scripts/setup-tests.sh
tests/integration/common/block_utils.rs
tests/integration/common/utils.rs
tests/integration/deprecated_syscalls_tests.rs

Feature: upgrade OS to 0.13.2

---

crates/bin/prove_block/src/reexecute.rs
crates/rpc-replay/src/rpc_state_reader.rs

Problem: similarly to what is happening for class hashes and nonces, we sometimes fetch storage values for non-existing contracts (ex: when the contract was deployed in the current block). When this happens, we fail on a `ContractNotFound` error in the RPC state reader and per-contract storage.
Solution: return 0 as default value when we do not find the storage.

Fix: return 0 as default storage value instead of error

---

crates/bin/prove_block/src/lib.rs
crates/bin/prove_block/src/state_utils.rs
crates/bin/prove_block/src/types.rs
crates/bin/prove_block/src/utils.rs
crates/bin/prove_block/tests/prove_block.rs
crates/rpc-replay/Cargo.toml
crates/rpc-replay/src/rpc_state_reader.rs
crates/rpc-replay/src/transactions.rs
crates/rpc-replay/tests/test_replay_block.rs

Problem: The code is not able to handle blocks with Declare transactions. 
Closes https://github.com/keep-starknet-strange/snos/issues/354
Solution: Add support for Declare transactions

Declare transaction support

---

crates/bin/prove_block/tests/prove_block.rs

Problem: we need to test blocks reporting dest_ptr issue
Fix: adds tests

add integration test for dest_ptr issue

---

Cargo.toml
crates/bin/prove_block/tests/prove_block.rs
crates/starknet-os/src/io/classes.rs

Problem: there was a missing case that was not fix by previous PR.
Solution: find out where the problem is and fix it. In order to fix this issue, a small part from a pathfinder's function was encapsulated and made public (related commit [here](https://github.com/Moonsong-Labs/pathfinder/commit/9c19d9a37be8f447ec4548456c440ccbd0e44260))
Closes https://github.com/keep-starknet-strange/snos/issues/379

Fix inconsistent hash

---

Cargo.lock
Cargo.toml

Fix cargo.toml to use correct cairo-vm branch. Push latest Cargo.lock

Fix Cargo.toml and update Cargo.lock

---

crates/bin/prove_block/src/lib.rs
crates/bin/prove_block/src/reexecute.rs
crates/bin/prove_block/src/state_utils.rs

Allow proving of blocks with height 0

feat: proving block with height 0

---

crates/rpc-client/src/state_reader/mod.rs

add: implement exp backoff retry logic for RPC calls in StateReader
