- .github/workflows/check.yml
- Cargo.toml
- src/utils/definitions/general_config.rs
- parse the test config from the OS repository
- util functions for default()
- try_from yaml
> feat: snos config parse

- scripts/list-hints.sh
It will return sorted and unique list of hints from os_latest.json:
```
scripts/list-hints.sh
[
{
"code": "# A builtin should be selected iff its encoding appears in the selected encodings list\n# and the list wasn't exhausted.\n# Note that testing inclusion by a single comparison is possible since the lists are sorted.\nids.select_builtin = int(\n  n_selected_builtins > 0 and memory[ids.selected_encodings] == memory[ids.all_encodings])\nif ids.select_builtin:\n  n_selected_builtins = n_selected_builtins - 1"
},
{
"code": "# Check that the actual return value matches the expected one.\nexpected = memory.get_range(\n    addr=ids.call_response.retdata, size=ids.call_response.retdata_size\n)\nactual = memory.get_range(addr=ids.retdata, size=ids.retdata_size)\n\nassert expected == actual, …
```
> Add list-hints script

- Cargo.lock
- src/error.rs
- src/hints/block_context.rs
- src/hints/execution.rs
- src/hints/mod.rs
- src/io/classes.rs
- src/io/input.rs
- src/io/mod.rs
- src/io/output.rs
- src/state/mod.rs
- src/utils.rs
- tests/common/prepared_os_test.rs
- tests/common/serde_utils.rs
- tests/snos.rs
After running `cargo update` I wasn't able to build the project anymore. As there is no rev for lambda class repo, I assume that we should keep with the head of the pointed branch.
Is that expected? Or should I close the PR and rely on the current implementation?
> dev: bump types to new version of starknet types

- src/execution/gas_constants.rs
- src/execution/mod.rs
- src/execution/syscall_handler.rs
- src/execution/syscall_utils.rs
- src/execution/syscalls.rs
- src/hints/execution.rs
- src/hints/mod.rs
- src/hints/syscalls.rs
- src/lib.rs
Infrastructure for executing Cairo1 syscalls. Executes first `GetExecutionInfo` syscall, fails on next `CallContract` syscall:
```
...
about to call contract_address: 3221225984, class_hash: 2147484160, is_deprecated: 0
about to execute syscall: GetExecutionInfo
about to execute syscall: CallContract
...
```
A lot of code borrowed from Blockifier. @odesenfans there are a lot of TODOs in syscalls.cairo. This code is adapted from blockifier. I prefer to move it in one go, put not ready parts in comments with todos, then uncomment one by one in subsequent prs.
> Syscall handler infra

- Cargo.lock
- cairo-type-derive/Cargo.toml
- cairo-type-derive/src/lib.rs
- src/cairo_types/traits.rs
Problem: the derive macro for `FieldOffsetGetters` assumes a size of 1 for each field of a struct, even if they are structures that span multiple felts.
Solution: take this into account in the offset computation. Deriving `FieldOffsetGetters` now adds a `cairo_size() -> usize` method that computes the size of the struct in terms of felts. This method is called for each struct encountered in the derive macro.
> Fix: support nested structures for `FieldOffsetGetters`

- src/hints/unimplemented.rs
This hint is already implemented as `TX_CALLDATA`.
> Cleanup: GEN_CALLDATA_ARG is already implemented

- src/hints/unimplemented.rs
This hint is already implemented as `TX_ENTRY_POINT_SELECTOR`.
> Cleanup: SET_AP_TO_ENTRY_POINT_SELECTOR is already implemented

- src/hints/unimplemented.rs
These hints are already implemented in cairo-vm.
> Cleanup: remove split input/output hint codes

- src/hints/mod.rs
- src/hints/output.rs
- src/hints/unimplemented.rs
- src/hints/vars.rs
> Feature: SET_TREE_STRUCTURE hint

- src/cairo_types/syscalls.rs
- src/hints/execution.rs
- src/hints/mod.rs
- src/hints/unimplemented.rs
This hint shares most of its implementation with the hint previously tagged as CACHE_CONTRACT_STORAGE. Renamed this hint to CACHE_CONTRACT_STORAGE_REQUEST_KEY and moved most of the code to a common implementation.
> Feature: CACHE_CONTRACT_STORAGE_SYSCALL_REQUEST_ADDRESS hint

- src/hints/unimplemented.rs
This hint is already implemented as `IS_REVERTED`.
> Cleanup: SET_AP_TO_IS_REVERTED is already implemented

- src/hints/execution.rs
- src/hints/mod.rs
- src/hints/unimplemented.rs
The CONTRACT_ADDRESS hint is declared in two places in the OS with a slightly different format.
> Cleanup: map second CONTRACT_ADDRESS hint declaration

- src/hints/unimplemented.rs
This hint is already implemented as TX_NONCE.
> Cleanup: SET_AP_TO_NONCE_OR_ZERO is already implemented

- Cargo.lock
- src/hints/output.rs
This version includes the `vm.get_output_builtin_mut()` and the `output_builtin.add_attribute()` methods. Fixed the workarounds for the absence of these methods.
> Chore: update cairo-vm to latest version

- src/hints/patricia.rs
- src/hints/state.rs
- src/hints/types.rs
Problem: the `__patricia_skip_validation_runner` part in several hints has been ignored so far and left as TODOs.
Solution: Now that the `PatriciaSkipValidationRunner` struct is upstreamed, added a utility function that checks if this option is configured and inserts the addresses to skip in the runner.
> Feature: support skipping validation of hashes

- src/cairo_types/syscalls.rs
- src/hints/execution.rs
- src/hints/mod.rs
- src/hints/unimplemented.rs
Hints introduced in #128 were deleted inadvertently. Reverted the change.
> Fix: restore CHECK_* hints that were deleted

- src/hints/state.rs
- src/hints/vars.rs
Fixed an error likely caused by a hasty copy-paste. The SET_PREIMAGE_FOR_CURRENT_COMMITMENT_INFO hint manipulates the initial/final contract state root variables and not `initial_root`/`final_root`.
> Fix: use correct initial/final state roots for commitment info hint

- src/hints/execution.rs
- src/hints/state.rs
- src/starknet/starknet_storage.rs
Problem: the implementation of this method was a stub.
Solution: port the Python implementation completely.
> Fix: implement `OsSingleStarknetStorage::new` the right way

- src/hints/state.rs
Fixed a TODO that resulted in a failure in the integration tests.
> Fix: get commitment info from `commitment_info_by_address`

- src/hints/execution.rs
- src/hints/mod.rs
This hint is not supposed to allocate a new segment.
> Fix: GET_CONTRACT_ADDRESS_STATE_ENTRY assigned to wrong hint

- src/hints/mod.rs
- src/hints/transaction_hash.rs
- src/hints/unimplemented.rs
- src/hints/vars.rs
> Feature: DATA_TO_HASH_NEW_SEGMENT hint

- src/hints/compiled_class.rs
- src/hints/mod.rs
- src/hints/unimplemented.rs
Implements the `ASSERT_END_OF_BYTECODE_SEGMENTS` hint.
> Impl ASSERT_END_OF_BYTECODE_SEGMENTS hint

- src/starkware_utils/commitment_tree/binary_fact_tree_node.rs
- src/starkware_utils/commitment_tree/patricia_tree/virtual_patricia_node.rs
- src/starkware_utils/commitment_tree/update_tree.rs
- src/storage/storage.rs
Problem: `OsSingleStarknetStorage` is currently built with a different FFC/storage for each contract. This creates N distinct storage objects while we should use one.
Solution: wrap the storage object inside an `Arc<Mutex<_>>` to make it shareable.
> Fix: share storage across contracts

- src/starknet/starknet_storage.rs
Problem: the commitment info height was incorrectly set to 0.
Solution: use the previous tree height, as is done in `cairo-lang`.
> Fix: pass correct tree height when building commitment info

- tests/common/transaction_utils.rs
Prints the last stack frame, also formatting it such that it can be opened easily in a text editor (e.g. `filename:line_number`)
> Print last stack frame in test

- src/cairo_types/builtins.rs
- src/hints/state.rs
Two fixes:
1. Use `get_ptr` instead of `get_relocatable`
2. Use `HashBuiltin` instead of `SpongeHashBuiltin` as this hint is encountered in `patricia.cairo` and not `patricia_with_sponge.cairo`.
> Fix: write hash_ptr.result correctly in LOAD_EDGE hint

- src/execution/deprecated_syscall_handler.rs
- src/execution/helper.rs
- src/hints/execution.rs
- src/hints/state.rs
- src/hints/syscalls.rs
- src/hints/tests.rs
- src/starknet/starknet_storage.rs
- src/storage/storage_utils.rs
- tests/integration/common/block_utils.rs
- tests/integration/common/transaction_utils.rs
- tests/integration/os.rs
Problem: we currently use the Blockifier state structures inside the OS. We wish to be agnostic of the data source inside the OS.
Solution: Add a mechanism to translate the Blockifier state into an OS-specific storage map at boot.
This fix allows to reach further in the OS execution.
> Feature: build storage from Blockifier state

- src/starknet/starknet_storage.rs
- src/starkware_utils/commitment_tree/binary_fact_tree.rs
- tests/integration/os.rs
Problem: when building `CommitmentInfo` objects, the `commitment_facts` field is left as an empty hashmap.
Solution: convert the (already built) hashmap properly and pass it when building the `CommitmentInfo` object.
> Fix: pass commitment fact in commitment info

- src/hints/patricia.rs
- tests/integration/os.rs
The `Descend` type is no longer required, we need to use the `DescentPath` type instead.
> Fix: use correct type for `descend`

- src/starkware_utils/commitment_tree/patricia_tree/patricia_guess_descents.rs
Operations must be performed on large integers to avoid overflows.
> Fix: overflow in descent map

- tests/integration/common/block_utils.rs
- tests/integration/os.rs
> Fix: use set_storage_at instead of storage_view when inserting block hash

- src/hints/patricia.rs
- src/hints/state.rs
- tests/integration/os.rs
This PR allows to reach the end of one iteration of the state update loop. The integration tests now fail on a missing contract in the commitment info.
Fixed the following issues (one issue per commit):
1. Wrong type used for the `node` variable
2. The `case` variable must be set in the scope in one of the preimage hints
3. Two instances of misuse of `get_ptr` vs `get_relocatable`.
> Fix: multiple issues related to the state update hints

- src/execution/helper.rs
- src/execution/syscall_handler.rs
- src/execution/syscall_utils.rs
- src/execution/syscalls.rs
- src/hints/mod.rs
- src/storage/storage_utils.rs
- tests/integration/common/block_utils.rs
- tests/integration/os.rs
Implements cairo1 deploy syscall. It is interesting because it uses state_diff to prepare os_hints data.
> Implement cairo1 deploy syscall

- tests/integration/common/block_utils.rs
- tests/integration/common/transaction_utils.rs
Moves block number mapping update to `execute_txs` out of `test_state`.
> Move block number mapping update out of `test_state`

- src/config.rs
This PR updates the `StarknetGeneralConfig` struct to reflect upstream changes (namely, removing `cairo_resource_fee_weights` as it was removed upstream.)
It also fixes an intermittent(-ish) test failure by changing the `Default` impl for `StarknetGeneralConfig` so that its behavior does not depend on the existence/contents of a default config file. This was causing the `parse_starknet_config` test to fail in some cases.
Instead, `Default` returns fixed values and a dedicated `fn from_default_file()` is provided (and used in the test).
> Update test expectations

- src/starknet/starknet_storage.rs
- src/starkware_utils/commitment_tree/base_types.rs
- src/starkware_utils/commitment_tree/patricia_tree/nodes.rs
- src/starkware_utils/serializable.rs
- src/storage/storage_utils.rs
Problem: we wish to implement `prefix()` for JSON-serializable structs, but this then requires to duplicate the implementation of the `serialize()` and `deserialize()` methods as there is no specialization in Rust.
Solution: move `prefix()` to the new `SerializationPrefix` trait.
> Internal: move `prefix()` from Serializable to new trait

- src/crypto/mod.rs
- src/crypto/poseidon.rs
Problem: we require an implementation of `HashFunctionType` for Poseidon hashing.
Solution: add a new `PoseidonHash` struct that uses starknet-crypto primitives.
> Feature: Poseidon hashing

- src/execution/deprecated_syscall_handler.rs
- src/execution/helper.rs
- src/execution/syscall_handler.rs
- src/execution/syscall_handler_utils.rs
- src/hints/execute_transactions.rs
- src/hints/execution.rs
- src/hints/mod.rs
- src/hints/state.rs
- src/hints/syscalls.rs
- src/hints/tests.rs
- src/starknet/starknet_storage.rs
- src/storage/storage_utils.rs
- src/utils.rs
- tests/integration/common/block_utils.rs
- tests/integration/common/transaction_utils.rs
- tests/integration/os.rs
Problem: we often encounter cases where `execute_coroutine_threadsafe()` causes a "cannot start a runtime from with a runtime" error. These errors are avoided by carefully placing the call. Ultimately, we have a lot of calls to `execute_coroutine_threadsafe()` deep inside the code and this is brittle.
Solution: acknowledge that most of the codebase needs to be async and handle sync -> async transitions from the highest level possible. Also, we now implement `execute_coroutine()` (we dropped the meaningless "threadsafe" suffix) to use `task::block_in_place` to run the coroutine on the calling thread. This is fine because we always end up here from the main thread running the OS.
Note that async tests must now use the `multi_thread` thread pool to enable using `task::block_in_place`, …
> Fix: improve handling of sync -> async calls in hints

- src/hints/patricia.rs
- src/utils.rs
Added a utility function to make the code used for PATRICIA_SKIP_VALIDATION_RUNNER reusable for other variables, if we ever need it.
> Internal: utility function to get root scope variable

- Cargo.lock
- Cargo.toml
- src/execution/deprecated_syscall_handler.rs
- src/hints/block_context.rs
- src/hints/execution.rs
- src/hints/mod.rs
- src/lib.rs
- src/starknet/business_logic/fact_state/state.rs
- src/starknet/business_logic/utils.rs
- src/starkware_utils/commitment_tree/binary_fact_tree.rs
- src/starkware_utils/commitment_tree/patricia_tree/patricia_utils.rs
- src/storage/dict_storage.rs
- src/storage/storage.rs
- tests/integration/common/block_utils.rs
- tests/integration/common/blockifier_contracts.rs
- tests/integration/common/state.rs
- tests/integration/common/transaction_utils.rs
Use the `log` and `env_logger` crates to display logs instead of `println!`.
Removed a few useless logs.
> Feature: logging

- tests/integration/common/block_utils.rs
- tests/integration/os.rs
This PR hooks up the state commitment info to the OsInput.
> Hook up state commitment info to OsInput

- src/crypto/pedersen.rs
- src/crypto/poseidon.rs
- src/starknet/business_logic/fact_state/contract_class_objects.rs
- src/starknet/business_logic/fact_state/contract_state_objects.rs
- src/starknet/business_logic/fact_state/state.rs
- src/starknet/business_logic/utils.rs
- src/starknet/starknet_storage.rs
- src/starkware_utils/commitment_tree/binary_fact_tree_node.rs
- src/starkware_utils/commitment_tree/calculation.rs
- src/starkware_utils/commitment_tree/patricia_tree/nodes.rs
- src/starkware_utils/commitment_tree/patricia_tree/patricia_tree.rs
- src/starkware_utils/commitment_tree/patricia_tree/virtual_calculation_node.rs
- src/starkware_utils/commitment_tree/patricia_tree/virtual_patricia_node.rs
- src/starkware_utils/commitment_tree/update_tree.rs
- src/storage/storage.rs
- src/storage/storage_utils.rs
- tests/integration/common/block_utils.rs
Problem: we did not use a custom type when porting most of the code, resulting in hashes being `Vec<u8>` all over the place. This is inconvenient and error-prone.
Solution: introduce the `Hash` type to encapsulate all hashes. With this, hashes are now type-safe and provide implementations of `From` for common types in Cairo VM and Starknet API.
> Internal: introduce the `Hash` type for hashes

- src/starknet/business_logic/fact_state/state.rs
- src/storage/storage_utils.rs
- tests/integration/common/block_utils.rs
- tests/integration/common/state.rs
- tests/integration/os.rs
Problem: the initial state creation for tests is messy and hard to
maintain.
Solution: introduce a builder pattern to make it easier to add contracts
and configure the initial state.
> Internal: clean up initial state creation

- src/hints/block_context.rs
- src/hints/mod.rs
- src/hints/patricia.rs
- src/hints/state.rs
- src/hints/types.rs
- src/hints/unimplemented.rs
- src/hints/vars.rs
- src/io/output.rs
- src/lib.rs
- tests/integration/common/block_utils.rs
- tests/integration/os.rs
Problem: we still pass an empty commitment info to the OS at startup.
Solution: use the correct class commitment info generated from the SharedState objects.
Additionally:
* Implement the `use_kzg_da` hint, note that the implementation only returns `false` for now.
* Added a mechanism to switch between Pedersen and Poseidon hashing in the Patricia hints. We enable a boolean flag after finishing the state update.
The tests now fail when building the OS output.
> Feature: enable class tree updates

- src/hints/types.rs
- src/io/mod.rs
- src/io/output.rs
- tests/integration/common/mod.rs
- tests/integration/common/transaction_utils.rs
- tests/integration/os.rs
Problem: the integration tests failed because the code to build the Starknet OS structure had never been used with real outputs.
Solution: reimplement the `from_run` method of `StarknetOsOutput`. The new version also supports KZG DA.
> Fix: build Starknet OS output struct from VM output

- src/cairo_types/structs.rs
- src/cairo_types/syscalls.rs
- src/execution/deprecated_syscall_handler.rs
- src/hints/execution.rs
> Fix: remove duplication in Cairo structs for deprecated syscalls

- src/hints/execution.rs
- src/starknet/business_logic/fact_state/contract_state_objects.rs
- src/starknet/business_logic/fact_state/state.rs
- src/starknet/starknet_storage.rs
- src/starkware_utils/commitment_tree/binary_fact_tree.rs
- src/starkware_utils/commitment_tree/patricia_tree/patricia_tree.rs
- src/starkware_utils/commitment_tree/patricia_tree/virtual_patricia_node.rs
Mutating the input and returning it is redundant. We now take ownership of the previous tree and return the updated one.
> Fix: make `BinaryFactTree::update` take self and not &mut self

- src/cairo_types/new_syscalls.rs
- src/cairo_types/syscalls.rs
- src/execution/deprecated_syscall_handler.rs
- src/execution/syscall_handler.rs
- src/hints/syscalls.rs
- tests/integration/main.rs
- tests/integration/syscalls_tests.rs
Added support and tests for the library_call syscall in deprecated and regular syscalls.
> Feature: library_call syscall for Cairo 0 and 1

- src/cairo_types/syscalls.rs
- src/execution/deprecated_syscall_handler.rs
- src/hints/syscalls.rs
- src/lib.rs
- tests/integration/syscalls_tests.rs
We now store a copy of `BlockInfo` in the deprecated syscall handler.
This copy can probably be removed in favor of a `Rc` or a reference,
this is out of scope for this PR.
> Feature: get block number and timestamp Cairo 0 syscalls

- src/cairo_types/structs.rs
- src/cairo_types/syscalls.rs
- src/execution/deprecated_syscall_handler.rs
- src/hints/execution.rs
- src/hints/syscalls.rs
- tests/integration/contracts/blockifier_contracts/feature_contracts/cairo0/compiled/test_contract_compiled.json
- tests/integration/contracts/blockifier_contracts/feature_contracts/cairo0/test_contract.cairo
- tests/integration/syscalls_tests.rs
Added support for `get_tx_info()` + a test.
Note that the test needed a new function in `test_contract.cairo` as the test for this syscall was impractical for integration testing.
> Feature: support Cairo 0 `get_tx_info()` syscall

- src/io/output.rs
- src/lib.rs
- tests/integration/common/transaction_utils.rs
Problem: the `contracts` and `classes` fields of the OS output are not deserialized correctly. We need to deserialize a full structure and not just felts.
Solution: add specific deserializers for contract and class changes. Additionally, add the OS output to the return value when running the OS in order to check specific output values in changes.
> Fix: load contract and class changes in OS output

- src/starknet/business_logic/fact_state/state.rs
- src/storage/storage_utils.rs
- tests/integration/common/state.rs
Problem: the `SharedState` struct has a `BlockInfo` member that is unused. This field is a relic of `cairo-lang`.
Solution: remove the field.
> Fix: remove `SharedState.block_info`

- src/hints/execution.rs
- src/utils.rs
Problem: Some hints would unwrap `Option`s instead of returning an error.
Solution: Replace unwraps with early error returns
> Fix: Remove panicking `unwrap`s in hints execution

- tests/integration/common/transaction_utils.rs
- tests/integration/declare_txn_tests.rs
- tests/integration/deploy_txn_tests.rs
- tests/integration/deprecated_syscalls_tests.rs
- tests/integration/l1_handler_txn_tests.rs
- tests/integration/os.rs
- tests/integration/syscalls_tests.rs
Problem: We need to be able to pass different types of txs as Transaction type
Solution: Pass the general type and convert
> Internal: Clean up the transaction types passed to execution

- Cargo.lock
- Cargo.toml
- src/storage/dict_storage.rs
- src/storage/storage.rs
Numerous methods of the trait are unused, and the API of `get_value` leaves to be desired when implementing complex storage types.
> Internal: simplify the Storage trait

- src/storage/cached_storage.rs
- src/storage/composite_storage.rs
- src/storage/mod.rs
Problem: we need storage capabilities to fetch data from an RPC, cache
the data locally and overall just combine multiple data sources for
production use cases.
Solution: introduce CompositeStorage, an implementation of the Storage
trait that enables fetching data from a main and fallback storage. This
enables caching, having some data stored locally and some fetched
dynamically from an RPC, etc.
> Feature: composite and cached storages

- .github/workflows/check.yml
Problem: sympy v1.13.0 moves some functions around, making it
incompatible with cairo-lang 0.13.1.
Solution: pin the version to any version before 1.13.0.
> Internal: fix CI tests by pinning sympy version

- src/hints/unimplemented.rs
Problem: some hints have been implemented in Cairo VM and our list is out of date.
Solution: update the list. Ran the hint tool and removed already implemented hints in `unimplemented.rs`.
> Chore: update list of unimplemented hints

- tests/integration/common/state.rs
- tests/integration/deploy_txn_tests.rs
Problem: for advanced integration tests, we need a way to add declared contracts to a test state without deploying them.
Solution: add two methods to declare Cairo 0/1 contracts in `StarknetStateBuilder`. Renamed the "add_*" methods to "deploy_*" to emphasize the difference.
> Internal: declare contracts in test states

- tests/integration/common/state.rs
- tests/integration/declare_txn_tests.rs
- tests/integration/deploy_txn_tests.rs
- tests/integration/deprecated_syscalls_tests.rs
- tests/integration/l1_handler_txn_tests.rs
- tests/integration/os.rs
- tests/integration/syscalls_tests.rs
Problem: when declaring contracts with the state builder, there is no easy way to find the declared contracts from the test state.
Solution: reproduce what is done for deployed contracts, give the user the ability to define a name for each declared contract.
> Internal: support giving names to declared contracts in tests

- Cargo.lock
- Cargo.toml
- bin/hint_tool/Cargo.toml
A release candidate finally incorporates all our changes, so we can stop using the git repository (at least for now).
> Chore: bump cairo-vm to 1.0.0-rc5

- crates/bin/hint_tool/src/main.rs
- crates/starknet-os/src/execution/deprecated_syscall_handler.rs
- crates/starknet-os/src/execution/helper.rs
- crates/starknet-os/src/execution/syscall_handler.rs
- crates/starknet-os/src/execution/syscall_handler_utils.rs
- crates/starknet-os/src/hints/execute_transactions.rs
- crates/starknet-os/src/hints/execution.rs
- crates/starknet-os/src/hints/mod.rs
- crates/starknet-os/src/hints/state.rs
- crates/starknet-os/src/hints/syscalls.rs
- crates/starknet-os/src/hints/tests.rs
- crates/starknet-os/src/hints/unimplemented.rs
- crates/starknet-os/src/lib.rs
- tests/integration/common/block_utils.rs
- tests/integration/common/transaction_utils.rs
Problem: for RPC compatibility, we need the OS to be compatible with user-defined storage types. This would allow, for example, to load storage values from an RPC at runtime.
Solution: make the execution helper generic on the storage type.
> Feature: make the OS generic on the storage type

- tests/integration/common/blockifier_contracts.rs
- tests/integration/common/contract_fixtures.rs
- tests/integration/common/mod.rs
- tests/integration/common/os_itest_contracts.rs
- tests/integration/common/state.rs
- tests/integration/common/utils.rs
- tests/integration/declare_txn_tests.rs
- tests/integration/deploy_txn_tests.rs
Problem: loading use-case specific test contracts (Blockifier feature contracts, OS itests) involves too much duplication.
Solution: provide generic functions to load a contract from its path in the `contract_fixtures` module and simplify the logic in specific modules to just get the path to contracts.
> Internal: make it easier to declare new test contracts

- crates/starknet-os/src/cairo_types/bigint.rs
- crates/starknet-os/src/cairo_types/builtins.rs
- crates/starknet-os/src/cairo_types/dict_access.rs
- crates/starknet-os/src/cairo_types/new_syscalls.rs
- crates/starknet-os/src/cairo_types/structs.rs
- crates/starknet-os/src/cairo_types/syscalls.rs
- crates/starknet-os/src/cairo_types/traits.rs
- rust-toolchain
- tests/integration/common/state.rs
Problem: The CI pipeline is broken because of new requirements for `udeps`.
Solution: bump the Rust toolchain to 1.78 nightly. The date of the build is the release date of Rust 1.78.
> Fix: bump Rust toolchain

- Cargo.toml
- crates/starknet-os/src/hints/tests.rs
Blockifier 0.6.0-rc.2 is used in production for cairo-lang 0.13.1 so we can safely use it.
> Chore: bump Blockifier to 0.6.0-rc.2

- Cargo.toml
It seems that `cairo-vm` released an `rc6` that Cargo jumped to (and is incompatible with SNOS right now), this fixes our version to `rc5`.
> Fix cairo-vm to v1.0.0-rc5

- Cargo.toml
- crates/starknet-os-types/Cargo.toml
- crates/starknet-os-types/src/hash.rs
- crates/starknet-os-types/src/lib.rs
- crates/starknet-os/Cargo.toml
- crates/starknet-os/src/crypto/pedersen.rs
- crates/starknet-os/src/crypto/poseidon.rs
- crates/starknet-os/src/starknet/business_logic/fact_state/contract_class_objects.rs
- crates/starknet-os/src/starknet/business_logic/fact_state/contract_state_objects.rs
- crates/starknet-os/src/starknet/business_logic/fact_state/state.rs
- crates/starknet-os/src/starknet/business_logic/utils.rs
- crates/starknet-os/src/starknet/starknet_storage.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/binary_fact_tree_node.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/calculation.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/patricia_tree/nodes.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/patricia_tree/patricia_tree.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/patricia_tree/virtual_calculation_node.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/patricia_tree/virtual_patricia_node.rs
- crates/starknet-os/src/storage/storage.rs
- crates/starknet-os/src/storage/storage_utils.rs
Problem: we need a single crate that defines useful types for all parts of the project. Useful types should be available from all the other crates.
Solution: introduce the `starknet-os-types` crate. Moved the `Hash` type there as a demonstration and preparation for upcoming PRs.
> Internal: introduce the `starknet-os-types` crate

- crates/starknet-os-types/src/hash.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/calculation.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/patricia_tree/patricia_tree.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/patricia_tree/virtual_calculation_node.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/patricia_tree/virtual_patricia_node.rs
Problem: as all the 32-byte wide types we use implement Copy, there is no
reason for `Hash` not to.
> Internal: derive `Copy` for `Hash`

- crates/starknet-os/src/cairo_types/syscalls.rs
- crates/starknet-os/src/execution/deprecated_syscall_handler.rs
Problem: the implementation of the `get_block_timestamp()` syscall was hastily copied from the implementation of `get_block_number()` and uses the wrong types. There is no functional problem because the types used have the same sizes, but this needs to be cleaned up.
Solution: define the request/response types and use them.
> Fix: copy-paste issues in the implementation of `get_block_timestamp()`

- crates/starknet-os/src/cairo_types/syscalls.rs
Problem: someone (me) was a little trigger-happy merging a PR that was not rebased, as we introduced stricter checks to the CI this PR broke the CI on main because of some warnings.
Solution: fix the problematic warnings.
> Fix: CI fails on main

- crates/starknet-os-types/Cargo.toml
- crates/starknet-os-types/src/contract_class.rs
- crates/starknet-os-types/src/hash.rs
- crates/starknet-os-types/src/lib.rs
- crates/starknet-os/src/hints/block_context.rs
- crates/starknet-os/src/io/classes.rs
- crates/starknet-os/src/io/input.rs
- crates/starknet-os/src/starknet/business_logic/fact_state/contract_class_objects.rs
- crates/starknet-os/src/starknet/business_logic/fact_state/state.rs
- crates/starknet-os/src/starknet/business_logic/utils.rs
- crates/starknet-os/src/storage/storage_utils.rs
- tests/Cargo.toml
- tests/integration/common/block_utils.rs
- tests/integration/common/blockifier_contracts.rs
- tests/integration/common/contract_fixtures.rs
- tests/integration/common/state.rs
- tests/integration/common/transaction_utils.rs
- tests/integration/declare_txn_tests.rs
Problem: we use different CASM contract classes depending on the use
case. We serialize/deserialize with the `cairo-lang` implementation, we
reexecute txs with the Blockifier implementation and we compute class
hashes through Pathfinder. Currently, we convert explicitly between
these types/crates. This makes the code harder to read and maintain.
Solution: introduce a generic class that is able to convert to/from all
the types we use under the hood. This puts a lid on the problem and
reduces the amount of code to change if things improve in the ecosystem.
> Feature: generic CASM class

- crates/starknet-os-types/Cargo.toml
- crates/starknet-os-types/src/contract_class.rs
- crates/starknet-os-types/src/deprecated_compiled_class.rs
- crates/starknet-os-types/src/error.rs
- crates/starknet-os-types/src/lib.rs
- crates/starknet-os/src/hints/deprecated_compiled_class.rs
- crates/starknet-os/src/io/input.rs
- crates/starknet-os/src/starknet/business_logic/fact_state/contract_class_objects.rs
- crates/starknet-os/src/starknet/business_logic/fact_state/state.rs
- crates/starknet-os/src/starknet/business_logic/utils.rs
- tests/integration/common/block_utils.rs
- tests/integration/common/blockifier_contracts.rs
- tests/integration/common/contract_fixtures.rs
- tests/integration/common/os_itest_contracts.rs
- tests/integration/common/state.rs
- tests/integration/common/transaction_utils.rs
- tests/integration/declare_txn_tests.rs
- tests/integration/run_os.rs
Problem: as for CASM classes, we use many different deprecated compiled
class types, creating a mess.
Solution: introduce `GenericDeprecatedCompiledClass`, a type that is
able to convert to all useful deprecated compiled class types and
to compute class hashes.
> Feature: generic deprecated compiled class

- crates/bin/prove_block/src/main.rs
This fixes the build. #298 renamed the `contract_class` module to `casm_contract_class` module without #287 noticing...
> Reflect renamed module (fix the build)

- crates/starknet-os-types/Cargo.toml
- crates/starknet-os-types/src/casm_contract_class.rs
Problem: our test coverage for compiled class hashing is lacking, and we are having trouble determining where hashing issues occur.
Solution: increase the coverage by porting tests from cairo-lang.
> Internal: port compiled class hash tests from cairo-lang

- crates/bin/hint_tool/src/main.rs
- crates/bin/prove_block/src/main.rs
- crates/starknet-os/src/execution/deprecated_syscall_handler.rs
- crates/starknet-os/src/execution/helper.rs
- crates/starknet-os/src/execution/syscall_handler.rs
- crates/starknet-os/src/execution/syscall_handler_utils.rs
- crates/starknet-os/src/hints/execute_transactions.rs
- crates/starknet-os/src/hints/execution.rs
- crates/starknet-os/src/hints/mod.rs
- crates/starknet-os/src/hints/state.rs
- crates/starknet-os/src/hints/syscalls.rs
- crates/starknet-os/src/hints/tests.rs
- crates/starknet-os/src/lib.rs
- crates/starknet-os/src/starknet/starknet_storage.rs
- crates/starknet-os/src/storage/storage_utils.rs
- tests/integration/common/block_utils.rs
- tests/integration/common/transaction_utils.rs
Problem: we are facing issues integrating the model of `OsSingleStarknetStorage` with Pathfinder, as we do not have a method to traverse the tree to reach arbitrary leaves.
Solution: Make the OS generic on the per-contract storage type instead of just the storage. This allows users to further customize the behaviour of the OS when it comes to storage.
> Feature: make OS per-contract storage customizable

- crates/starknet-os/src/hints/compiled_class.rs
- crates/starknet-os/src/hints/mod.rs
- crates/starknet-os/src/starknet/core/os/contract_class/compiled_class_hash_objects.rs
This pull request implements SET_AP_TO_SEGMENT_HASH and hash functions for `BytecodeSegmentedNode` and `BytecodeSegmentStructureImpl`
> Feature: SET_AP_TO_SEGMENT_HASH hint

- Cargo.toml
- crates/rpc-replay/src/rpc_state_reader.rs
- crates/starknet-os-types/Cargo.toml
- crates/starknet-os-types/src/deprecated_compiled_class.rs
- crates/starknet-os-types/src/lib.rs
- crates/starknet-os-types/src/starknet_core_addons.rs
Problem: the conversion from starknet-core `CompressedLegacyContractClass` in `GenericDeprecatedContractClass` is untested and broken. This class cannot be used interchangeably with other deprecated contract classes because the `program` field is deserialized as a gzip bytes vector.
Solution: add conversion functions to decompress the program field and generate a `LegacyContractClass` from it before storing it in the generic class.
> Fix: decompress starknet-core legacy class

- crates/bin/prove_block/src/rpc_utils.rs
Problem: we panic on some [apparently] non-fatal errors during contract proof validation, namely that the proof depth is not always 251.
Solution: `log::warn!()` instead of panic.
> Log proof validation failure instead of panicking

- crates/bin/prove_block/src/types.rs
- crates/rpc-replay/src/transactions.rs
Problem: conversion from starknet-core invoke v3 txs to Blockifier transactions is unimplemented.
Solution: implement it.
> Feature: support invoke v3 txs in `prove_block`

- crates/rpc-replay/src/transactions.rs
Problem: We can't easily distinguish between calls to `unimplemented!()` when no string is passed to it
Solution: pass a unique string to each call
> Pass identifying string to unimplemented!() calls

- crates/bin/prove_block/src/main.rs
- crates/starknet-os-types/src/chain_id.rs
- crates/starknet-os-types/src/lib.rs
- crates/starknet-os/src/config.rs
- crates/starknet-os/src/hints/block_context.rs
- tests/integration/common/transaction_utils.rs
- tests/integration/deprecated_syscalls_tests.rs
Problems:
* we hardcode the chain to `SN_GOERLI` in hash computations
* we are inconsistent in our usage of `ChainId`, we sometimes fill it with a hex string while we should use the chain name in human-readable format in all cases.
Solution: let the caller specify the chain in `execute_txs_and_run_os` and clean our usage of `ChainId`.
> Feature: enable specifying the chain in integration tests

- crates/rpc-replay/src/block_context.rs
Problem: transactions that use blob data (`l1_da_mode` set to "BLOB" in
the block) cannot be reexecuted because of incorrect gas computations.
Solution: set `use_kzg_da` in the block info according to the
`l1_da_mode` in the block structure.
> Fix: set `use_kzg_da` in block info based on RPC data

- .github/workflows/prove_blocks.yml
- crates/bin/prove_block/src/reexecute.rs
- crates/bin/prove_block/src/utils.rs
- crates/starknet-os/src/hints/execution.rs
- crates/starknet-os/src/hints/mod.rs
Problem: we panic explicitly if a block contains a reverted transaction, and the OS fails if we remove these panics.
Solution: Fix support for reverted transactions. This PR simply implements the `IS_REVERTED` hint correctly and removes panic/unimplemented calls.
> Feature: support reverted transactions

- crates/bin/prove_block/src/types.rs
Problem: the version for this tx type is set to 2, causing an issue with these txs where the OS fails on `tx.max_fee is None`.
Solution: set the transaction version to 3.
> Fix: use correct transaction version for invoke v3

- crates/bin/prove_block/src/lib.rs
- crates/bin/prove_block/src/state_utils.rs
- crates/bin/prove_block/tests/prove_block.rs
- crates/starknet-os-types/src/compiled_class.rs
- crates/starknet-os-types/src/lib.rs
Problem: some blocks fail on divergences in the global state tree caused by calls to the `replace_class()` syscall.
Solution: use the class hash in block N-1 when building the `ContractClass` objects instead of the current block, and fetch the compiled class for both blocks to build the trees properly.
> Fix: support `replace_class()` calls in invoke txs

- crates/bin/prove_block/src/utils.rs
- crates/rpc-replay/src/transactions.rs
Problem PR https://github.com/keep-starknet-strange/snos/pull/330 was too big
Solution: split the PR into smaller PR where each one will implement a different transaction. 
Clean up and modularize Invoke tx
> clean up Invoke tx

- crates/bin/prove_block/src/lib.rs
- crates/bin/prove_block/src/state_utils.rs
- crates/bin/prove_block/src/utils.rs
- crates/bin/prove_block/tests/prove_block.rs
- crates/rpc-replay/src/transactions.rs
- crates/rpc-replay/tests/test_replay_block.rs
Problem PR https://github.com/keep-starknet-strange/snos/pull/330 was too big
Solution: split the PR into smaller PR where each one will implement a different transaction.
Support for L1 Handler transaction.
Block 98000 added to CI regression tests
> L1 handler tx

- Cargo.toml
- crates/bin/prove_block/src/rpc_utils.rs
> Chore: bump Blockifier to 0.8.0-rc.3

- crates/bin/prove_block/src/state_utils.rs
- crates/bin/prove_block/src/utils.rs
Problem: Library calls do not have a distinct contract address (they use the caller's address in their context), so looking only at contract addresses in subcalls prevents us from ever loading these classes.
Solution: Record classes while traversing subcall tree and load them.
> Fix: Get classes out of subcalls

- crates/bin/prove_block/src/lib.rs
- crates/bin/prove_block/src/reexecute.rs
- crates/bin/prove_block/src/rpc_utils.rs
- crates/bin/prove_block/src/state_utils.rs
- crates/bin/prove_block/tests/prove_block.rs
- crates/rpc-replay/src/rpc_state_reader.rs
Problem: the setup for `prove_block` assumes that we are always able to fetch the class hash, class and storage proof for the contract addresses found in invoke txs in the previous block. This is not always the case as invoke txs are able to deploy contracts.
Solution: accept "contract not found" errors and storage proofs where the `contract_data` field is missing. Note that we should implement a way to double-check our expectations as this fix will accept an incomplete storage proof in the current block as well, which is not ideal.
> Fix: support invoke txs that call the deploy syscall

- crates/bin/prove_block/tests/prove_block.rs
Problem: Block `87041` had exhibited `nonce bump inconsistency`
Solution: Add it to prove block integration tests
> add: block 87041 with nonce bump inconsistency

- crates/bin/prove_block/src/lib.rs
- crates/bin/prove_block/src/state_utils.rs
Problem: for some reason, we do not pass Cairo 0 compiled classes in the OS input, despite computing them.
Solution: add them to the formatted state update and pass them to the OS input.
> Fix: pass deprecated compiled classes to the OS input

- Cargo.toml
- crates/bin/prove_block/Cargo.toml
- crates/bin/prove_block/src/lib.rs
- crates/bin/prove_block/src/reexecute.rs
- crates/bin/prove_block/src/rpc_utils.rs
- crates/bin/prove_block/src/state_utils.rs
- crates/rpc-client/Cargo.toml
- crates/rpc-client/src/client.rs
- crates/rpc-client/src/lib.rs
- crates/rpc-client/src/pathfinder/client.rs
- crates/rpc-client/src/pathfinder/mod.rs
- crates/rpc-client/src/pathfinder/proofs.rs
- crates/rpc-replay/Cargo.toml
- crates/rpc-replay/src/rpc_state_reader.rs
- crates/rpc-replay/tests/test_replay_block.rs
Problems:
* We manage two types of clients, one for Starknet RPC endpoints and another for Pathfinder proof endpoints.
* We end up spawning way more clients than necessary because the starknet-rs client type does not implement Clone.
Solution: encapsulate all RPC-related objects in a new struct, `RpcClient`. This struct lives in the new `rpc-client` crate.
* Moved all the code related to proofs in the `rpc-client` crate.
* Updated `rpc-replay` and `prove-block` to use the new RPC client.
* Added a layer to encapsulate the raw `reqwest` client used for Pathfinder proof endpoints in the new `PathfinderRpcClient` struct.
At this stage `RpcClient` still provides direct access to the Starknet and Pathfinder RPC clients, and does not implement anything fancy (read: caching). The goal of this PR …
> Feature: rpc-client crate

- crates/bin/prove_block/src/lib.rs
This prints `inner_exc` clearly on its own line. This is usually the error message that's interesting, and it's otherwise buried and difficult to visually scan for. This also makes it practical to `grep` it.
> Explicitly print inner_exc error

- rustfmt.toml
Problem: `cargo fmt` will mangle comments to make them fit on one line. This causes problems especially when code is commented out, but also seems to fight me when I want a multi-line comment to look a specific way.
Solution: remove `wrap_comments = true` from `rustfmt.toml`, allowing the default (true) to kick in.
Documentation: https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#wrap_comments
> Dev: Don't wrap comments with cargo fmt

- Cargo.toml
- crates/bin/prove_block/tests/prove_block.rs
Adds test to cover the previously-missing EvalCircuit hint.
~~Points to https://github.com/Moonsong-Labs/cairo-vm/pull/44~~
Currently points to `79cefb786f407ad0536db253e86017d3c4039f5e` which is on branch `notlesh/snos-rc-2024-09-13`. This contains PRs 41, 43, and 44
Issue Number: #366
> Add block test to cover missing EvalCircuit hint

- crates/starknet-os-types/src/casm_contract_class.rs
- crates/starknet-os-types/src/deprecated_compiled_class.rs
- crates/starknet-os-types/src/sierra_contract_class.rs
Problem: `prove_block` can't be used across threads because some structs internally use `Rc`.
Solution: Replace `Rc` with `Arc`.
This supercedes #368 as part of fixing #364.
Issue Number: #364
> Fix: Use Arc instead of Rc in GenericFoo structs

- crates/starknet-os/src/hints/find_element.rs
- crates/starknet-os/src/hints/mod.rs
- crates/starknet-os/src/hints/tests.rs
`search_sorted_optimistic` was previously called `find_element` and has been renamed to match the correct Cairo function it's called from, since there are three variations of very similar hint code.
> Added tests for `fill_holes_in_rc96_segment` and `search_sorted_optimistic` hints

- crates/bin/prove_block/src/state_utils.rs
- crates/bin/prove_block/tests/prove_block.rs
Problem: Some blocks contain a Declare and in the same block a Deploy transaction. This condition triggers an error in `find_element` hint from cairo-vm
Solution:
The solution consists in setting two hash maps that are used by snos with the correct information.
For declare transactions:
`class_hash_to_compiled_class_hash: HashMap<ClassHash, CompiledClassHash>` needs to be initialized with Zero for all new classes
For deploy transactions:
`compiled_classes: HashMap<CompiledClassHash, GenericCasmContractClass>` needs to be set with the compiled_class_hash from declared class and the corresponding binary.
Issue Number: https://github.com/keep-starknet-strange/snos/issues/376
Closes #376
> Fix: find_element(): No value found for key

- crates/starknet-os/src/hints/execution.rs
Reverts keep-starknet-strange/snos#381
> Revert "fix: The enter syscall scopes hint is wrongly formatted."

- Cargo.toml
- crates/bin/prove_block/tests/prove_block.rs
- tests/integration/common/transaction_utils.rs
Problem: We weren't performing validation checks on the PIEs we were generating.
Fix: Adds run_validity_checks() in our prove block tests
> Test: add pie validity check to prove block

- .github/workflows/prove_blocks.yml
- crates/bin/prove_block/Cargo.toml
- crates/bin/prove_block/tests/hash_tests.rs
- crates/bin/prove_block/tests/prove_block.rs
- crates/starknet-os-types/src/starknet_core_addons.rs
- pyproject.toml
Problem: for some Cairo0 contracts, computation from `class_hash` was incorrect. This was preventing from executing some new blocks that use old contracts
Solution: fix the hash computation
Issue Number: #379
> Fix inconsistent class hash

- crates/bin/prove_block/src/lib.rs
- crates/bin/prove_block/src/main.rs
- crates/bin/prove_block/tests/prove_block.rs
- crates/starknet-os/src/io/output.rs
- scripts/prove-blocks.sh
The reference PIE was created with `full_output` enabled, so `output.rs` was updated to support that. The code was also refactored to better mirror the Cairo serialization code.
> Enabled `full_output` and using reference PIE to validate our PIEs are correct

- crates/starknet-os/src/hints/kzg.rs
Problem:
The bug was that the commitment split returned by this function was wrong. I encountered this when I was integrating the snos with madara orchestrator and performing an e2e test. On the final step of the block processing the contract was giving an error saying that "precompile evaluation failed". After debugging we found out that this is the issue the commitment returned by the snos was wrong.
> fix: `split_commitment` function in KZG data availability implementation

- crates/bin/prove_block/src/state_utils.rs
- crates/bin/prove_block/tests/prove_block.rs
Problem: while trying to process latest blocks we bumped into KeyNotInProof error. It seems that there are different issues that trigger the same error.
Solution: Remove deprecated classes from `class_hash_compiled_class_hash` map. This will fix part of the failing blocks that present KeyNotInProof error.
> Fix blocks with KeyNotInProof (part 1)

- crates/bin/prove_block/tests/prove_block.rs
Problem: some blocks fail with this error: `inner_exc error: Got an exception while executing a hint: Missing constant: MAX_HIGH`
Solution: Since this seems to be a bug in cairo-vm, we've implemented a default value for MAX_HIGH and MAX_LOW if they are not found on the `constants` HashMap.
Related PR: https://github.com/Moonsong-Labs/cairo-vm/pull/47
In order to get the CI in green, the previous PR has to be merged. Current snos project points to the branch, so it's not needed to update Cargo.toml
> Missing constant MAX_HIGH

- Cargo.toml
- tests/integration/pie.rs
Problem: serialize/deserialize is not properly working
Fix: cairo-vm serialize function was not expecting new builtins (fixed [here](https://github.com/Moonsong-Labs/cairo-vm/pull/48/files))
> Fix: Serialize pie function

- Cargo.lock
- crates/bin/output_segment/src/main.rs
- crates/bin/prove_block/src/lib.rs
- crates/bin/prove_block/src/main.rs
- crates/bin/prove_block/tests/prove_block.rs
Problem: We had the COMPILED_OS constant in lib.rs, making it impossible for consumers to define the compiled_os while using SNOS as lib. 
Fix: Move it again to main.rs in correspondent binaries
> remove COMPILED_OS const from lib

- crates/bin/prove_block/src/lib.rs
- crates/bin/prove_block/src/reexecute.rs
- crates/bin/prove_block/tests/prove_block.rs
Problem:
Certain blocks encountered different errors when processed with SNOS. Upon closer inspection, discrepancies were identified between the transaction traces provided by Pathfinder and the internal re-execution using Blockifier. Since both components essentially utilize the same parts of Blockifier, and the traces accurately reflect the network's state, we determined that the traces could serve as a source of truth.
Solution:
Identify the differences in how Pathfinder executes transactions using Blockifier and apply the necessary adjustments. This PR calls `pre_process_block` before executing the transactions that was missing.
Closes https://github.com/keep-starknet-strange/snos/issues/434
Fix blocks: `161599`, `174156`, `161884` and `174027`
> Fix reexecute with blockifier

- crates/starknet-os/src/hints/state.rs
Add new test for `state.rs` load_bottom hint.
> Add load_bottom hint test

- crates/starknet-os/src/config.rs
- crates/starknet-os/src/utils.rs
Remove unused code from `starknet-os/utils.rs` file.
Add unit tests to `starknet-os/utils.rs` file.
> Improve starknet-os/utils code

- crates/bin/prove_block/src/lib.rs
- crates/starknet-os/src/execution/deprecated_syscall_handler.rs
- crates/starknet-os/src/execution/helper.rs
- crates/starknet-os/src/hints/execution.rs
- crates/starknet-os/src/hints/syscalls.rs
- crates/starknet-os/src/hints/tests.rs
- tests/integration/common/block_utils.rs
With https://github.com/keep-starknet-strange/snos/pull/419 and https://github.com/keep-starknet-strange/snos/pull/393 merged, the execution helper no longer needs the os input.
> Remove os input from execution helper

- crates/starknet-os/src/hints/compression.rs
- crates/starknet-os/src/hints/dict.rs
- crates/starknet-os/src/hints/math.rs
- crates/starknet-os/src/hints/mod.rs
This PR provides:
- Fixes on handling felts, uses `BigUint`.
- Fixes on keeping the order of insertion, replaces `HashMap` with `IndexMap`.
- Fixes minor logical errors in the `compress` implementation.
- Adds parameterised tests for the `compress` method.
> fix: handle `full_output` compression correctly

- crates/starknet-os/src/hints/compression.rs
- crates/starknet-os/src/hints/constants.rs
- crates/starknet-os/src/hints/math.rs
- crates/starknet-os/src/hints/mod.rs
- crates/starknet-os/src/hints/vars.rs
Latest feature from OS upgrade to v0.13.3. This PR includes the compression hint that was the missing part to get all the tests from the CI in ✅
Supersedes #463 
> Compression hint

- crates/starknet-os/src/hints/compression.rs
- crates/starknet-os/src/hints/mod.rs
- crates/starknet-os/src/io/output.rs
This PR allows decompressing of the output to produce a state diff when both `use_kzg_da` and `full_output` are 0
> feat: decompress the output to state diff

- .github/workflows/check.yml
- Cargo.lock
- Cargo.toml
- crates/rpc-client/src/pathfinder/proofs.rs
- crates/starknet-os-types/Cargo.toml
- crates/starknet-os-types/src/casm_contract_class.rs
- crates/starknet-os-types/src/deprecated_compiled_class.rs
- crates/starknet-os-types/src/hash.rs
- crates/starknet-os-types/src/lib.rs
- crates/starknet-os-types/src/sierra_contract_class.rs
- crates/starknet-os/src/hints/tests.rs
- crates/starknet-os/src/starknet/business_logic/fact_state/state.rs
- crates/starknet-os/src/starkware_utils/commitment_tree/patricia_tree/virtual_patricia_node.rs
- rust-toolchain
This PR avoids the need for a `nightly` rust compiler by avoiding the `once_cell_try` feature. This is accomplished by using the `once_cell` crate instead of `std::cell`.
> Use crate once_cell instead of std::cell

- crates/bin/prove_block/src/main.rs
This allows writing a processed pie to a file.
> add: ability to write a proved pie to a path

- .github/workflows/check.yml
- crates/rpc-replay/src/transactions.rs
- rust-toolchain
- tests/integration/common/transaction_utils.rs
- tests/integration/declare_txn_tests.rs
Currently we don't support v0 declare txns. 
We need to:
**Related Code**
```
thread 'main' panicked at ~/snos/crates/rpc-replay/src/transactions.rs:368:42:
not implemented: starknet_rs_to_blockifier with DeclareTransaction::V0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Issue Number: #470
> feat: add support for declare v0 txns

- .github/workflows/check.yml
- crates/bin/prove_block/tests/prove_block.rs
This PR attempts to fix an issue where the stable toolchain was not available in CI.
It also disables a test that is currently triggering a bug in `pathfinder`, hopefully this is temporary.
> bug(ci): Also install stable toolchain

- crates/bin/prove_block/src/lib.rs
- crates/rpc-client/src/pathfinder/proofs.rs
This works around an issue introduced when Pathfinder [removed `class_commitment` from its class proof](https://github.com/eqlabs/pathfinder/pull/2452).
The proofs we get back from `Pathfinder` (prior to v0.8 RPC) are in order. What that means is that the proof is a list of MPT nodes, ordered such that you can walk through the proof from top-to-bottom. This implies that the first node is always the root node, which is the same thing as the `commitment`. In other words, we can get the root/commitment by simply looking at the first node, and that's what this PR does.
Note, however, that this is redundant -- `verify_proof()` ultimately hashes the root node and compares that to `class_commitment`, which is exactly what this PR does. It would be just as good to make `class_commitment` an …
> Calculate class_commitment from proof

- crates/bin/prove_block/src/utils.rs
- crates/starknet-os/src/execution/deprecated_syscall_handler.rs
- crates/starknet-os/src/hints/syscalls.rs
- tests/integration/run_os.rs
Currently the `delegate_syscall` had been silenced with a noop `storage_write`. 
This PR fixes that and adds a test in the run_os tests to ensure that the call is handled correctly
This PR also adds `code_addresses` to the map of `accessed_storage_keys` so that the os can successfully access the storage for contracts that were only invoked in a delegate_call.
> fix: handle delegate_call syscalls correctly

- Cargo.lock
- Cargo.toml
This PR updates the specific versions of cairo-lang from 2.8.2 to 2.8.4 and fixes the cairo-vm (fork) branch used by external users such as madara.
This allows parity of the deps used by snos and madara.
It also allows them to use v0.13.3 of the os.
> deps: update cairo-lang and cairo-vm
